channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal =5.7.0
  - bbmap =38.75
  - bedtools =2.29.2
  - pigz =2.4
  - fastqc =0.11.8
  - multiqc =1.7
  - trimmomatic =0.38
  - star =2.7.3a
  - picard =2.18.7
  - samtools =1.9
  - subread =1.6.4

